### ISSUE TITLE
Livereload does not work

### ISSUE THREAD

**Issue by chmar77** [farism/elm-factory#3]
After editing elm files, it does not auto reload the page.

**Comment by farism** [comment]
Could you give me some more information as to your current project environment? Which operating system? Is this on a project that was created with `elm-factory`, or another elm project? Are you running in any type of VM?

**Comment by farism** [comment]
I have released two versions since this issue and have had other people confirm this working, so closing for now. Feel free to add any additional feedback if this still persists.
